import type { Metadata } from "next";
import { Syncopate, Quicksand, Syne } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/lib/convex/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { I18nProvider } from "@/lib/i18n/provider";
import enDict from "@/dictionaries/en.json";
import { LenisProvider } from "@/components/providers/LenisProvider";

// Syncopate for headings - bold, impactful comic-style font
const syncopate = Syncopate({
  weight: ["400", "700"],
  variable: "--font-syncopate",
  subsets: ["latin"],
  display: "swap",
});

// Quicksand for body text - clean, friendly, readable
const quicksand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
  subsets: ["latin"],
  display: "swap",
});

// Syne for alternative headings/display text
const syne = Syne({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-syne",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Disable static optimization for this layout since it uses client-side auth
export const dynamic = "force-dynamic";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${syncopate.variable} ${quicksand.variable} ${syne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-quicksand">
        <ConvexAuthNextjsServerProvider>
          <I18nProvider initialLocale="en" initialDictionary={enDict}>
            <ConvexClientProvider>
              <LenisProvider>{children}</LenisProvider>
            </ConvexClientProvider>
          </I18nProvider>
        </ConvexAuthNextjsServerProvider>
      </body>
    </html>
  );
}
